### ISSUE TITLE
GPU inference? 

### ISSUE THREAD

**Issue by Yogevsho** [JorianWoltjer/transcribe-to-premiere#5] opened 2023-09-28 08:34 UTC
Hey again :)
is it possible to transfer between CPU \ GPU inference? trying to improve trancription speed using larger models (medium\large).
thank you in advance!

**Comment by JorianWoltjer** [comment] 2023-09-28 09:57
I'm not sure what you mean by "GPU I inference" as I'm not that deep into AI. Do you simply mean running the tool using your GPU? In that case, you just need the GPU version of Torch as explained in the README.md file. 

Let me know if that helps or if you have a different issue

**Comment by Yogevsho** [comment] 2023-10-02 00:00
Hey again and thank you for your patience. Yes, that is what im talking about. Although i installed the gpu version of torch, the tool still uses my cpu rather than my gpu. 

I saw the repo owner of stable-ts giving an example of something like this when he talked about using cpu/gpu:

model = whisper.load_model('large-v2', device="cpu")
stable_whisper.modify_model(model)

But it’s not with the load_faster_whisper that we currently use here so idk 🤷🏼‍♂️
Any idea how can i use the tool with my gpu or what did i do wrong? 

thanks in advance!

**Comment by JorianWoltjer** [comment] 2023-10-02 07:14
Reading [this line](https://github.com/guillaumekln/faster-whisper/blob/5a0541ea7d054aa3716ac492491de30158c20057/faster_whisper/transcribe.py#L83) makes me think faster-whisper automatically detects the cuda option, which I can confirm by adding a small line in between [L38-L39](https://github.com/JorianWoltjer/AutoCaptions/blob/master/transcribe.py#L38-L39):
```diff
  model = load_faster_whisper(model_name)
+ print(model.model.device)
  log.success("Loaded Whisper model")
```
This prints `cuda` when ran on my own laptop, because it detects my GPU. The model also seems to be much faster on my end so I'm pretty sure it's using that GPU. 

My guess would be there is some other issue with your CUDA or torch for why it is not recognizing it. 
1. Did you receive a warning or anything how you know it is using your CPU instead?
2. Do any other Python projects using CUDA work for your GPU?

**Comment by Yogevsho** [comment] 2023-10-02 12:27
> Reading [this line](https://github.com/guillaumekln/faster-whisper/blob/5a0541ea7d054aa3716ac492491de30158c20057/faster_whisper/transcribe.py#L83) makes me think faster-whisper automatically detects the cuda option, which I can confirm by adding a small line in between [L38-L39](https://github.com/JorianWoltjer/AutoCaptions/blob/master/transcribe.py#L38-L39):
> 
> ```diff
>   model = load_faster_whisper(model_name)
> + print(model.model.device)
>   log.success("Loaded Whisper model")
> ```
> 
> This prints `cuda` when ran on my own laptop, because it detects my GPU. The model also seems to be much faster on my end so I'm pretty sure it's using that GPU.
> 
> My guess would be there is some other issue with your CUDA or torch for why it is not recognizing it.
> 
> 1. Did you receive a warning or anything how you know it is using your CPU instead?
> 2. Do any other Python projects using CUDA work for your GPU?

Well it’s weird - I’ve added that line the same as you did, and it showed that it’s using cuda. However, while im using the app and looking at my Performances tab in the Task Manager, im seeing that the cpu is working (climbs up to 70% at times) while the percentages on the GPU isnt moving or going up, indicating that it’s put to use.

do i get something wrong? Missing something?

**Comment by JorianWoltjer** [comment] 2023-10-02 13:03
Interesting. On my laptop the CPU stays around 20-30%, and the GPU goes up and down from 0 to 4-5%. When I compare that with *forcing* it to use the CPU instead of CUDA, there is a big difference:
```diff
- model = load_faster_whisper(model_name)
+ model = load_faster_whisper(model_name, device="cpu")
```
CPU goes to around 50-60% and GPU stays 0 always. The time it takes to transcribe is also around 10x slower. 

Can you try forcing it to use the CPU like above and comparing the time it takes to see if it is significantly slower? If not, then it might indeed be using the CPU by default for some reason.

**Comment by Yogevsho** [comment] 2023-10-02 13:48
Well i tried it and indeed it was much slower than before. also i noticed that in the original method (using the gpu, i guess), it is writing 'cuda' in the cmd. 
but still, when im using the app the CPU usage % goes up and the gpu slightly moves, much less than the cpu column. 

Maybe this is how it's supposed to be? i mean does it make sense that the process is happening on the gpu but still the cpu% goes up like this? i just expected to see more usage of the gpu and little to none on the cpu, which isn't the current situation 🤷🏼‍♂

**Comment by JorianWoltjer** [comment] 2023-10-02 14:06
I also guess that this is intentional. Often not all work can be done on the GPU and only very specific tasks are given to it that it can perform quickly. Maybe with the "large" model, there is more of a noticeable usage jump. 

The fact that setting it to CPU makes it much slower confirms that it was indeed using your GPU. On my machine, the GPU also moves only slightly to around 4-5%. For this reason, I'll close the issue now because I don't see a possible improvement atm.

**Closed as completed by JorianWoltjer** 2023-10-02 14:06 UTC
